name: 'Storm CMS Components'
description: 'Storm CMS Components wrapper'
install:
  - block_content
  - views
  - entity_browser
  - entity_reference_display
  - iframe
  - layout_builder_browser
  - material_icons
  - paragraphs
  - viewsreference
config:
  import:
    block_content:
      - field.storage.block_content.body
      - core.entity_view_mode.block_content.full
      - views.view.block_content
    material_icons: "*"
    paragraphs: "*"
