name: 'Storm CMS Components'
description: 'Storm CMS Components wrapper'
install:
  - block_content
  - views
  - layout_builder_browser
config:
  import:
    block_content:
      - field.storage.block_content.body
      - core.entity_view_mode.block_content.full
      - views.view.block_content
